# action.yml
name: 'Opcache Reset'
description: 'Reset PHP opcache on the server'
inputs:
  domain: 
    description: 'The domain to visit to clear opcache for'
    required: true
  webroot:
    description: "The path of the site's webroot"
    required: true
  php_executable:
    description: 'The PHP executable to use'
    required: false
    default: 'php'
  owner:
    description: 'The user who should own the file'
    required: false
  group:
    description: 'The group the file should belong to'
    required: false
  permissions:
    description: 'The octal permissions to use'
    required: false
    default: "644"
  ssh_user:
    description: 'The user to connect to the server as'
    required: true
  ssh_host:
    description: 'The hostname or IP to use for connecting via SSH'
    required: true
  ssh_port:
    description: 'The SSH port for the server'
    required: false
    default: "22"
  ssh_key:
    description: 'The SSH key for connecting to the server'
    required: true
  retries_opcache_reset_http:
    description: 'The number of times to retry the opcache reset HTTP request'
    required: false
    default: "3"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.domain }}
    - ${{ inputs.webroot }}
    - ${{ inputs.php_executable }}
    - ${{ inputs.owner }}
    - ${{ inputs.group }}
    - ${{ inputs.permissions }}
    - ${{ inputs.ssh_user }}
    - ${{ inputs.ssh_host }}
    - ${{ inputs.ssh_port }}
    - ${{ inputs.ssh_key }}
    - ${{ inputs.retries_opcache_reset_http }}
